#!/usr/bin/env bash
function handle_signit()
{
    for proc in $(jobs -p)
    do
        kill $proc
    done
}

trap handle_sigint SIGINT

PYRO_SERIALIZERS_ACCEPTED=serpent,pickle python2 -m Pyro4.naming -n localhost &

wait

